id: P009245
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN6495
  title: དཔྱལ་གྱི་གདུང་རབས་ཟ་ར་ཚགས་དང་གང་གཱའི་ཆུ་རྒྱུན་གཉིས་གཅིག་ཏུ་བྲིས་པ་ཀུན་གསལ་མེ་ལོང་།
  author: ''
  volumes:
    fae25189cb5c45769a658128b3bde97d:
      image_group_id: I3CN6497
      title: ''
      volume_number: 1
      total_pages: 138
      base_file: v001.txt
