id: IAA20BA1A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T09:29:13+00:00'
last_modified: '2022-06-08T09:38:51.945605+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN6495
  title: དཔྱལ་གྱི་གདུང་རབས་ཟ་ར་ཚགས་དང་གང་གཱའི་ཆུ་རྒྱུན་གཉིས་གཅིག་ཏུ་བྲིས་པ་ཀུན་གསལ་མེ་ལོང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '4383':
      image_group_id: I3CN6497
      title: ''
      total_pages: 138
      order: 1
      base_file: 4383.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
